const DATA = [
  {
    id: "0",
    name: "russia",
    countries: "russia",
    availableOperators: "any",
  },
  {
    id: "1",
    name: "ukraine",
    countries: "ukraine",
    availableOperators: "any",
  },
  {
    id: "2",
    name: "kazakhstan",
    countries: "kazakhstan",
    availableOperators: "any",
  },
  {
    id: "3",
    name: "china",
    countries: "china",
    availableOperators: "any",
  },
  {
    id: "4",
    name: "philippines",
    countries: "philippines",
    availableOperators: "any",
  },
  {
    id: "5",
    name: "myanmar",
    countries: "myanmar",
    availableOperators: "any",
  },
  {
    id: "6",
    name: "indonesia",
    countries: "indonesia",
    availableOperators: "any",
  },
  {
    id: "7",
    name: "malaysia",
    countries: "malaysia",
    availableOperators: "any",
  },
  {
    id: "8",
    name: "kenya",
    countries: "kenya",
    availableOperators: "any",
  },
  {
    id: "9",
    name: "tanzania",
    countries: "tanzania",
    availableOperators: "any",
  },
  {
    id: "10",
    name: "vietnam",
    countries: "vietnam",
    availableOperators: "any",
  },
  {
    id: "11",
    name: "kyrgyzstan",
    countries: "kyrgyzstan",
    availableOperators: "any",
  },
  {
    id: "12",
    name: "usa",
    countries: "usa",
    availableOperators: "any",
  },
  {
    id: "13",
    name: "israel",
    countries: "israel",
    availableOperators: "any",
  },
  {
    id: "14",
    name: "hongkong",
    countries: "hongkong",
    availableOperators: "any",
  },
  {
    id: "15",
    name: "poland",
    countries: "poland",
    availableOperators: "any",
  },
  {
    id: "16",
    name: "england",
    countries: "england",
    availableOperators: "any",
  },
  {
    id: "17",
    name: "madagascar",
    countries: "madagascar",
    availableOperators: "any",
  },
  {
    id: "18",
    name: "dcongo",
    countries: "dcongo",
    availableOperators: "any",
  },
  {
    id: "19",
    name: "nigeria",
    countries: "nigeria",
    availableOperators: "any",
  },
  {
    id: "20",
    name: "macao",
    countries: "macao",
    availableOperators: "any",
  },
  {
    id: "21",
    name: "egypt",
    countries: "egypt",
    availableOperators: "any",
  },
  {
    id: "22",
    name: "india",
    countries: "india",
    availableOperators: "any",
  },
  {
    id: "23",
    name: "ireland",
    countries: "ireland",
    availableOperators: "any",
  },
  {
    id: "24",
    name: "cambodia",
    countries: "cambodia",
    availableOperators: "any",
  },
  {
    id: "25",
    name: "laos",
    countries: "laos",
    availableOperators: "any",
  },
  {
    id: "26",
    name: "haiti",
    countries: "haiti",
    availableOperators: "any",
  },
  {
    id: "27",
    name: "ivory",
    countries: "ivory",
    availableOperators: "any",
  },
  {
    id: "28",
    name: "gambia",
    countries: "gambia",
    availableOperators: "any",
  },
  {
    id: "29",
    name: "serbia",
    countries: "serbia",
    availableOperators: "any",
  },
  {
    id: "30",
    name: "yemen",
    countries: "yemen",
    availableOperators: "any",
  },
  {
    id: "31",
    name: "southafrica",
    countries: "southafrica",
    availableOperators: "any",
  },
  {
    id: "32",
    name: "romania",
    countries: "romania",
    availableOperators: "any",
  },
  {
    id: "33",
    name: "colombia",
    countries: "colombia",
    availableOperators: "any",
  },
  {
    id: "34",
    name: "estonia",
    countries: "estonia",
    availableOperators: "any",
  },
  {
    id: "35",
    name: "azerbaijan",
    countries: "azerbaijan",
    availableOperators: "any",
  },
  {
    id: "36",
    name: "canada",
    countries: "canada",
    availableOperators: "any",
  },
  {
    id: "37",
    name: "morocco",
    countries: "morocco",
    availableOperators: "any",
  },
  {
    id: "38",
    name: "ghana",
    countries: "ghana",
    availableOperators: "any",
  },
  {
    id: "39",
    name: "argentina",
    countries: "argentina",
    availableOperators: "any",
  },
  {
    id: "40",
    name: "uzbekistan",
    countries: "uzbekistan",
    availableOperators: "any",
  },
  {
    id: "41",
    name: "cameroon",
    countries: "cameroon",
    availableOperators: "any",
  },
  {
    id: "42",
    name: "chad",
    countries: "chad",
    availableOperators: "any",
  },
  {
    id: "43",
    name: "germany",
    countries: "germany",
    availableOperators: "any",
  },
  {
    id: "44",
    name: "lithuania",
    countries: "lithuania",
    availableOperators: "any",
  },
  {
    id: "45",
    name: "croatia",
    countries: "croatia",
    availableOperators: "any",
  },
  {
    id: "46",
    name: "sweden",
    countries: "sweden",
    availableOperators: "any",
  },
  {
    id: "47",
    name: "iraq",
    countries: "iraq",
    availableOperators: "any",
  },
  {
    id: "48",
    name: "netherlands",
    countries: "netherlands",
    availableOperators: "any",
  },
  {
    id: "49",
    name: "latvia",
    countries: "latvia",
    availableOperators: "any",
  },
  {
    id: "50",
    name: "austria",
    countries: "austria",
    availableOperators: "any",
  },
  {
    id: "51",
    name: "belarus",
    countries: "belarus",
    availableOperators: "any",
  },
  {
    id: "52",
    name: "thailand",
    countries: "thailand",
    availableOperators: "any",
  },
  {
    id: "53",
    name: "saudiarabia",
    countries: "saudiarabia",
    availableOperators: "any",
  },
  {
    id: "54",
    name: "mexico",
    countries: "mexico",
    availableOperators: "any",
  },
  {
    id: "55",
    name: "taiwan",
    countries: "taiwan",
    availableOperators: "any",
  },
  {
    id: "56",
    name: "spain",
    countries: "spain",
    availableOperators: "any",
  },
  {
    id: "57",
    name: "iran",
    countries: "iran",
    availableOperators: "any",
  },
  {
    id: "58",
    name: "algeria",
    countries: "algeria",
    availableOperators: "any",
  },
  {
    id: "59",
    name: "slovenia",
    countries: "slovenia",
    availableOperators: "any",
  },
  {
    id: "60",
    name: "bangladesh",
    countries: "bangladesh",
    availableOperators: "any",
  },
  {
    id: "61",
    name: "senegal",
    countries: "senegal",
    availableOperators: "any",
  },
  {
    id: "62",
    name: "turkey",
    countries: "turkey",
    availableOperators: "any",
  },
  {
    id: "63",
    name: "czech",
    countries: "czech",
    availableOperators: "any",
  },
  {
    id: "64",
    name: "srilanka",
    countries: "srilanka",
    availableOperators: "any",
  },
  {
    id: "65",
    name: "peru",
    countries: "peru",
    availableOperators: "any",
  },
  {
    id: "66",
    name: "pakistan",
    countries: "pakistan",
    availableOperators: "any",
  },
  {
    id: "67",
    name: "newzealand",
    countries: "newzealand",
    availableOperators: "any",
  },
  {
    id: "68",
    name: "guinea",
    countries: "guinea",
    availableOperators: "any",
  },
  {
    id: "69",
    name: "mali",
    countries: "mali",
    availableOperators: "any",
  },
  {
    id: "70",
    name: "venezuela",
    countries: "venezuela",
    availableOperators: "any",
  },
  {
    id: "71",
    name: "ethiopia",
    countries: "ethiopia",
    availableOperators: "any",
  },
  {
    id: "72",
    name: "mongolia",
    countries: "mongolia",
    availableOperators: "any",
  },
  {
    id: "73",
    name: "brazil",
    countries: "brazil",
    availableOperators: "any",
  },
  {
    id: "74",
    name: "afghanistan",
    countries: "afghanistan",
    availableOperators: "any",
  },
  {
    id: "75",
    name: "uganda",
    countries: "uganda",
    availableOperators: "any",
  },
  {
    id: "76",
    name: "angola",
    countries: "angola",
    availableOperators: "any",
  },
  {
    id: "77",
    name: "cyprus",
    countries: "cyprus",
    availableOperators: "any",
  },
  {
    id: "78",
    name: "france",
    countries: "france",
    availableOperators: "any",
  },
  {
    id: "79",
    name: "papua",
    countries: "papua",
    availableOperators: "any",
  },
  {
    id: "80",
    name: "mozambique",
    countries: "mozambique",
    availableOperators: "any",
  },
  {
    id: "81",
    name: "nepal",
    countries: "nepal",
    availableOperators: "any",
  },
  {
    id: "82",
    name: "belgium",
    countries: "belgium",
    availableOperators: "any",
  },
  {
    id: "83",
    name: "bulgaria",
    countries: "bulgaria",
    availableOperators: "any",
  },
  {
    id: "84",
    name: "hungary",
    countries: "hungary",
    availableOperators: "any",
  },
  {
    id: "85",
    name: "moldova",
    countries: "moldova",
    availableOperators: "any",
  },
  {
    id: "86",
    name: "italy",
    countries: "italy",
    availableOperators: "any",
  },
  {
    id: "87",
    name: "paraguay",
    countries: "paraguay",
    availableOperators: "any",
  },
  {
    id: "88",
    name: "honduras",
    countries: "honduras",
    availableOperators: "any",
  },
  {
    id: "89",
    name: "tunisia",
    countries: "tunisia",
    availableOperators: "any",
  },
  {
    id: "90",
    name: "nicaragua",
    countries: "nicaragua",
    availableOperators: "any",
  },
  {
    id: "91",
    name: "timorleste",
    countries: "timorleste",
    availableOperators: "any",
  },
  {
    id: "92",
    name: "bolivia",
    countries: "bolivia",
    availableOperators: "any",
  },
  {
    id: "93",
    name: "costarica",
    countries: "costarica",
    availableOperators: "any",
  },
  {
    id: "94",
    name: "guatemala",
    countries: "guatemala",
    availableOperators: "any",
  },
  {
    id: "95",
    name: "uae",
    countries: "uae",
    availableOperators: "any",
  },
  {
    id: "96",
    name: "zimbabwe",
    countries: "zimbabwe",
    availableOperators: "any",
  },
  {
    id: "97",
    name: "puertorico",
    countries: "puertorico",
    availableOperators: "any",
  },
  {
    id: "99",
    name: "togo",
    countries: "togo",
    availableOperators: "any",
  },
  {
    id: "100",
    name: "kuwait",
    countries: "kuwait",
    availableOperators: "any",
  },
  {
    id: "101",
    name: "salvador",
    countries: "salvador",
    availableOperators: "any",
  },
  {
    id: "102",
    name: "libyan",
    countries: "libyan",
    availableOperators: "any",
  },
  {
    id: "103",
    name: "jamaica",
    countries: "jamaica",
    availableOperators: "any",
  },
  {
    id: "104",
    name: "trinidad",
    countries: "trinidad",
    availableOperators: "any",
  },
  {
    id: "105",
    name: "ecuador",
    countries: "ecuador",
    availableOperators: "any",
  },
  {
    id: "106",
    name: "swaziland",
    countries: "swaziland",
    availableOperators: "any",
  },
  {
    id: "107",
    name: "oman",
    countries: "oman",
    availableOperators: "any",
  },
  {
    id: "108",
    name: "bosnia",
    countries: "bosnia",
    availableOperators: "any",
  },
  {
    id: "109",
    name: "dominican",
    countries: "dominican",
    availableOperators: "any",
  },
  {
    id: "110",
    name: "syrian",
    countries: "syrian",
    availableOperators: "any",
  },
  {
    id: "111",
    name: "qatar",
    countries: "qatar",
    availableOperators: "any",
  },
  {
    id: "112",
    name: "panama",
    countries: "panama",
    availableOperators: "any",
  },
  {
    id: "113",
    name: "cuba",
    countries: "cuba",
    availableOperators: "any",
  },
  {
    id: "114",
    name: "mauritania",
    countries: "mauritania",
    availableOperators: "any",
  },
  {
    id: "115",
    name: "sierraleone",
    countries: "sierraleone",
    availableOperators: "any",
  },
  {
    id: "116",
    name: "jordan",
    countries: "jordan",
    availableOperators: "any",
  },
  {
    id: "117",
    name: "portugal",
    countries: "portugal",
    availableOperators: "any",
  },
  {
    id: "118",
    name: "barbados",
    countries: "barbados",
    availableOperators: "any",
  },
  {
    id: "119",
    name: "burundi",
    countries: "burundi",
    availableOperators: "any",
  },
  {
    id: "120",
    name: "benin",
    countries: "benin",
    availableOperators: "any",
  },
  {
    id: "121",
    name: "brunei",
    countries: "brunei",
    availableOperators: "any",
  },
  {
    id: "122",
    name: "bahamas",
    countries: "bahamas",
    availableOperators: "any",
  },
  {
    id: "123",
    name: "botswana",
    countries: "botswana",
    availableOperators: "any",
  },
  {
    id: "124",
    name: "belize",
    countries: "belize",
    availableOperators: "any",
  },
  {
    id: "125",
    name: "caf",
    countries: "caf",
    availableOperators: "any",
  },
  {
    id: "126",
    name: "dominica",
    countries: "dominica",
    availableOperators: "any",
  },
  {
    id: "127",
    name: "grenada",
    countries: "grenada",
    availableOperators: "any",
  },
  {
    id: "128",
    name: "georgia",
    countries: "georgia",
    availableOperators: "any",
  },
  {
    id: "129",
    name: "greece",
    countries: "greece",
    availableOperators: "any",
  },
  {
    id: "130",
    name: "guineabissau",
    countries: "guineabissau",
    availableOperators: "any",
  },
  {
    id: "131",
    name: "guyana",
    countries: "guyana",
    availableOperators: "any",
  },
  {
    id: "132",
    name: "iceland",
    countries: "iceland",
    availableOperators: "any",
  },
  {
    id: "133",
    name: "comoros",
    countries: "comoros",
    availableOperators: "any",
  },
  {
    id: "134",
    name: "saintkitts",
    countries: "saintkitts",
    availableOperators: "any",
  },
  {
    id: "135",
    name: "liberia",
    countries: "liberia",
    availableOperators: "any",
  },
  {
    id: "136",
    name: "lesotho",
    countries: "lesotho",
    availableOperators: "any",
  },
  {
    id: "137",
    name: "malawi",
    countries: "malawi",
    availableOperators: "any",
  },
  {
    id: "138",
    name: "namibia",
    countries: "namibia",
    availableOperators: "any",
  },
  {
    id: "139",
    name: "niger",
    countries: "niger",
    availableOperators: "any",
  },
  {
    id: "140",
    name: "rwanda",
    countries: "rwanda",
    availableOperators: "any",
  },
  {
    id: "141",
    name: "slovakia",
    countries: "slovakia",
    availableOperators: "any",
  },
  {
    id: "142",
    name: "suriname",
    countries: "suriname",
    availableOperators: "any",
  },
  {
    id: "143",
    name: "tajikistan",
    countries: "tajikistan",
    availableOperators: "any",
  },
  {
    id: "144",
    name: "monaco",
    countries: "monaco",
    availableOperators: "any",
  },
  {
    id: "145",
    name: "bahrain",
    countries: "bahrain",
    availableOperators: "any",
  },
  {
    id: "146",
    name: "reunion",
    countries: "reunion",
    availableOperators: "any",
  },
  {
    id: "147",
    name: "zambia",
    countries: "zambia",
    availableOperators: "any",
  },
  {
    id: "148",
    name: "armenia",
    countries: "armenia",
    availableOperators: "any",
  },
  {
    id: "149",
    name: "somalia",
    countries: "somalia",
    availableOperators: "any",
  },
  {
    id: "150",
    name: "congo",
    countries: "congo",
    availableOperators: "any",
  },
  {
    id: "151",
    name: "chile",
    countries: "chile",
    availableOperators: "any",
  },
  {
    id: "152",
    name: "burkinafaso",
    countries: "burkinafaso",
    availableOperators: "any",
  },
  {
    id: "153",
    name: "lebanon",
    countries: "lebanon",
    availableOperators: "any",
  },
  {
    id: "154",
    name: "gabon",
    countries: "gabon",
    availableOperators: "any",
  },
  {
    id: "155",
    name: "albania",
    countries: "albania",
    availableOperators: "any",
  },
  {
    id: "156",
    name: "uruguay",
    countries: "uruguay",
    availableOperators: "any",
  },
  {
    id: "157",
    name: "mauritius",
    countries: "mauritius",
    availableOperators: "any",
  },
  {
    id: "158",
    name: "bhutan",
    countries: "bhutan",
    availableOperators: "any",
  },
  {
    id: "159",
    name: "maldives",
    countries: "maldives",
    availableOperators: "any",
  },
  {
    id: "160",
    name: "guadeloupe",
    countries: "guadeloupe",
    availableOperators: "any",
  },
  {
    id: "161",
    name: "turkmenistan",
    countries: "turkmenistan",
    availableOperators: "any",
  },
  {
    id: "162",
    name: "frenchguiana",
    countries: "frenchguiana",
    availableOperators: "any",
  },
  {
    id: "163",
    name: "finland",
    countries: "finland",
    availableOperators: "any",
  },
  {
    id: "164",
    name: "saintlucia",
    countries: "saintlucia",
    availableOperators: "any",
  },
  {
    id: "165",
    name: "luxembourg",
    countries: "luxembourg",
    availableOperators: "any",
  },
  {
    id: "166",
    name: "saintvincentgrenadines",
    countries: "saintvincentgrenadines",
    availableOperators: "any",
  },
  {
    id: "167",
    name: "equatorialguinea",
    countries: "equatorialguinea",
    availableOperators: "any",
  },
  {
    id: "168",
    name: "djibouti",
    countries: "djibouti",
    availableOperators: "any",
  },
  {
    id: "169",
    name: "antiguabarbuda",
    countries: "antiguabarbuda",
    availableOperators: "any",
  },
  {
    id: "170",
    name: "caymanislands",
    countries: "caymanislands",
    availableOperators: "any",
  },
  {
    id: "171",
    name: "montenegro",
    countries: "montenegro",
    availableOperators: "any",
  },
  {
    id: "172",
    name: "denmark",
    countries: "denmark",
    availableOperators: "any",
  },
  {
    id: "173",
    name: "switzerland",
    countries: "switzerland",
    availableOperators: "any",
  },
  {
    id: "174",
    name: "norway",
    countries: "norway",
    availableOperators: "any",
  },
  {
    id: "175",
    name: "australia",
    countries: "australia",
    availableOperators: "any",
  },
  {
    id: "176",
    name: "eritrea",
    countries: "eritrea",
    availableOperators: "any",
  },
  {
    id: "177",
    name: "southsudan",
    countries: "southsudan",
    availableOperators: "any",
  },
  {
    id: "178",
    name: "saotomeandprincipe",
    countries: "saotomeandprincipe",
    availableOperators: "any",
  },
  {
    id: "179",
    name: "aruba",
    countries: "aruba",
    availableOperators: "any",
  },
  {
    id: "180",
    name: "montserrat",
    countries: "montserrat",
    availableOperators: "any",
  },
  {
    id: "181",
    name: "anguilla",
    countries: "anguilla",
    availableOperators: "any",
  },
  {
    id: "183",
    name: "northmacedonia",
    countries: "northmacedonia",
    availableOperators: "any",
  },
  {
    id: "184",
    name: "seychelles",
    countries: "seychelles",
    availableOperators: "any",
  },
  {
    id: "185",
    name: "newcaledonia",
    countries: "newcaledonia",
    availableOperators: "any",
  },
  {
    id: "186",
    name: "capeverde",
    countries: "capeverde",
    availableOperators: "any",
  },
  {
    id: "187",
    name: "usaphysical",
    countries: "usaphysical",
    availableOperators: "any",
  },
  {
    id: "189",
    name: "fiji",
    countries: "fiji",
    availableOperators: "any",
  },
  {
    id: "196",
    name: "singapore",
  },
];

export const COUNTRIES_DATA = (() =>
  DATA.sort((a, b) => {
    if (a.name > b.name) {
      return 1;
    }
    if (a.name < b.name) {
      return -1;
    }
    return 0;
  }))();
